# -*- coding: utf-8 -*-
from . import account_move
from . import product
from . import stock_gadgets
from . import stock_gadgets_types_assistance
from . import stock_gadgets_state
from . import stock_gadgets_use
from . import stock_gadgets_contract_type
from . import stock_gadgets_increase_type
from . import stock_gadgets_billing_period
from . import stock_gadgets_maintenance_frequency
from . import stock_elevator_type
from . import stock_soil_type
from . import stock_cockpit_keypad_type
from . import stock_cockpit_push_type
from . import stock_bench
from . import stock_shipment
from . import stock_wash_cabin
from . import stock_landing_keypad
from . import stock_landing_lock
from . import stock_landing_doors
from . import stock_maneuvering_table
from . import stock_types_cabin_tubes
from . import stock_bidirectional_model
from . import stock_gsm_model
from . import stock_landing_key
from . import stock_gadgets_planning_type
from . import stock_state_record
from . import stock_location
